baseurl = "https://colour.jsbarretto.com/"
languageCode = "en-gb"
title = "Colourised Photographs"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Joshua Barretto"
	description = "Your photographs, colourised by hand"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.avatar]
		hide = true


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		#avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Joshua**.<br>I bring history to life by<br>colourising old photographs."
		# The icons will be shown if you enter your username
		twitter = "jsbarretto"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Joshua Barretto",
			"Design: [HTML5 UP](//html5up.net)",
		]


	[params.about]
		hide  = false
		title = "Colourised Photographs"
		content = """The lack of colour in old photographs is often an obstacle to our appreciation of them. Without colour, we may only experience the past at an arm's distance. Without colour, history becomes less accessible. By colourising old black and white photographs by hand, we can make the past feel as real as the present. Adding colour changes the way we think about the past.<br><br> \
		<a href="#contact-form">You can order your own colourised photograph here.</a>"""


	[params.portfolio]
		hide  = false
		title = "Colourisations"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like

		[[params.portfolio.gallery]]
			image = "/thumb/alice-bacon.png"
			thumb = "/thumb/alice-bacon.png"
			title = "Alice Bacon"
			description = "Labour MP and Chair of the UK Labour Party 1950-1970"

		[[params.portfolio.gallery]]
			image = "/thumb/tony-benn.png"
			thumb = "/thumb/tony-benn.png"
			title = "Tony Benn"
			description = "British Postmaster General and Minister of Technology 1964-1970"

		[[params.portfolio.gallery]]
			image = "/thumb/judith-hart.png"
			thumb = "/thumb/judith-hart.png"
			title = "Judith Hart"
			description = "Minister for Overseas Development and Chair of the UK Labour Party 1977-1982"

		[[params.portfolio.gallery]]
			image = "/thumb/arthur-greenwood.png"
			thumb = "/thumb/arthur-greenwood.png"
			title = "Arthur Greenwood"
			description = "Minister of Health and Deputy Leader of the UK Labour Party 1929-1945"

		[[params.portfolio.gallery]]
			image = "/thumb/jennie-lee.png"
			thumb = "/thumb/jennie-lee.png"
			title = "Jennie Lee"
			description = "British Minister for Arts 1964-1970"

		[[params.portfolio.gallery]]
			image = "/thumb/hugh-foot.png"
			thumb = "/thumb/hugh-foot.png"
			title = "Hugh Foot"
			description = "British Minister of State for Foreign Affairs and British Ambassador to the United Nations 1964-1970"

		[[params.portfolio.gallery]]
			image = "/thumb/herbert-morrison.png"
			thumb = "/thumb/herbert-morrison.png"
			title = "Herbert Morrison"
			description = "Leader of the House of Commons and Deputy British Prime Minister 1945-1951"

		[[params.portfolio.gallery]]
			image = "/thumb/lucy-middleton.png"
			thumb = "/thumb/lucy-middleton.png"
			title = "Lucy Middleton"
			description = "Labour MP for Plymouth Sutton 1945-1951"

		[[params.portfolio.gallery]]
			image = "/thumb/caroline-ganley.png"
			thumb = "/thumb/caroline-ganley.png"
			title = "Caroline Ganley"
			description = "Labour and Co-operative MP for Battersea South 1945-1951"

		[[params.portfolio.gallery]]
			image = "/thumb/aneurin-bevan.png"
			thumb = "/thumb/aneurin-bevan.png"
			title = "Aneurin Bevan"
			description = "British Minister for Health and Housing 1945-1951"

		[[params.portfolio.gallery]]
			image = "/thumb/margaret-bondfield.png"
			thumb = "/thumb/margaret-bondfield.png"
			title = "Margaret Bondfield"
			description = "First British female cabinet minister and Labour MP 1923-1931"

		[[params.portfolio.gallery]]
			image = "/thumb/stafford-cripps.png"
			thumb = "/thumb/stafford-cripps.png"
			title = "Stafford Cripps"
			description = "British Chancellor of the Exchequer and Minister for Aircraft Production 1942-1950"

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Order a colourised photograph"
		content = """Colourised photographs make perfect gifts for friends and family. You can request a quote for a photograph colourisation using the form below.<br><br> \
		Please be aware of the following. \
		<ul> \
			<li>Colourising is a time-consuming process. The minimum price for a colourised image is therefore £15</li> \
			<li>I do not yet provide a photo framing service, so I can only provide you with a digital final image</li> \
			<li>I have limited hours in a day. If I have a backlog of requests to fill, I may not have time to colourise your photograph</li> \
			<li>Colourising is not an exact science. Please provide as much information about colour in the original as possible (e.g: eye and hair colour)</li> \
		</ul>"""

		# This can be exact coordinates or a searchable address in google maps
		#gmaps_address = "39.7889055,-120.5443524"
		#address = [
		#	"1234 Somewhere Rd.",
		#	"Nashville, TN 00000",
		#	"United States"
		#]
		#phone = "+447927 037265"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "joshua@jsbarretto.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Description of photograph"
			submit = "Send message"

# Menu links that appear on the left sidebar
[[menu.main]]
	#name = "Home"
	url  = "/"
	weight = 10

#[[menu.main]]
#	name = "Blog"
#	url  = "post/"
#	weight = 0
